"""Terraform integration: render intent ops as .tf files.

Direction: 'terraform-out', not 'terraform-in'. We don't ingest existing
state — we just emit a Terraform configuration that recreates what the
intent op would have built. This lets the user choose whether to execute
via boto3 (fast, scriptable) or terraform (durable, declarative, drift-
aware).

Output goes to terraform/<customer>/main.tf, gitignored alongside
customers/.

The first use case is jumphost; pattern generalizes.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

from .. import tagging


SKILL_ROOT = Path(__file__).resolve().parents[2]
TERRAFORM_DIR = SKILL_ROOT / "terraform"


def render_jumphost(
    *,
    customer: str,
    allowed_ip: Optional[str] = None,
    instance_type: Optional[str] = None,
    environment: str = "dev",
    out_dir: Optional[Path] = None,
) -> dict[str, Any]:
    """Emit a self-contained main.tf for a customer jump host.

    Mirrors what `intent.jumphost.provision()` would create:
      - aws_key_pair (caller supplies the public-key material via tfvar)
      - aws_security_group + aws_security_group_rule (port 22 from CIDR)
      - aws_instance (Ubuntu 22.04 LTS via SSM parameter lookup)
      - aws_eip + aws_eip_association

    Returns: paths of files written + the suggested apply commands.
    """
    cfg = tagging.load_customer_config(customer)
    if not cfg:
        raise ValueError(
            f"customers/{customer}.json not found. Cannot render Terraform "
            "without a customer config."
        )

    region = cfg.get("region", "us-west-2")
    naming_prefix = cfg.get("naming_prefix", customer)
    jh = cfg.get("jumphost", {})
    instance_type = (
        instance_type or jh.get("instance_type") or "t4g.small"
    )
    allowed = allowed_ip or (jh.get("allowed_ingress") or [None])[0]
    if not allowed:
        raise ValueError(
            "No allowed-ingress CIDR. Pass --allowed-ip or set "
            f"customers/{customer}.json jumphost.allowed_ingress."
        )

    target_dir = Path(out_dir) if out_dir else (TERRAFORM_DIR / customer)
    target_dir.mkdir(parents=True, exist_ok=True)

    tags = tagging.build_tags(
        customer=customer, project="jumphost", environment=environment
    )

    main_tf = _render_main_tf(
        customer=customer,
        naming_prefix=naming_prefix,
        region=region,
        instance_type=instance_type,
        allowed_cidr=allowed,
        tags=tags,
    )
    variables_tf = _render_variables_tf(naming_prefix=naming_prefix)
    outputs_tf = _render_outputs_tf()
    user_data = _read_user_data(naming_prefix, allowed)

    files: dict[str, Path] = {
        "main.tf": target_dir / "main.tf",
        "variables.tf": target_dir / "variables.tf",
        "outputs.tf": target_dir / "outputs.tf",
        "user-data.sh": target_dir / "user-data.sh",
    }
    files["main.tf"].write_text(main_tf)
    files["variables.tf"].write_text(variables_tf)
    files["outputs.tf"].write_text(outputs_tf)
    files["user-data.sh"].write_text(user_data)

    return {
        "customer": customer,
        "region": region,
        "out_dir": str(target_dir),
        "files": {k: str(v) for k, v in files.items()},
        "next_steps": [
            f"cd {target_dir}",
            "terraform init",
            "Generate an SSH key locally (the .tf reads its public-key path "
            "from var.public_key_path).",
            "terraform plan",
            "terraform apply",
        ],
        "notes": (
            "This is a stand-alone Terraform module. State is local by "
            "default; for shared use, configure an S3 backend. The module "
            "intentionally does not import existing skill-managed resources."
        ),
    }


# ---- Templates --------------------------------------------------------------


def _render_main_tf(
    *,
    customer: str,
    naming_prefix: str,
    region: str,
    instance_type: str,
    allowed_cidr: str,
    tags: dict[str, str],
) -> str:
    tags_block = _render_tag_block(tags, indent="    ")
    return f"""# aws-skill / Terraform — jumphost for customer: {customer}
# Generated by lib/intent/terraform.py
#
# Mirrors what `aws_skill.py jumphost provision --customer {customer}` would create.
# Edit the variables in variables.tf, then `terraform init && terraform apply`.

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
  required_version = ">= 1.5"
}}

provider "aws" {{
  region  = "{region}"
  profile = var.aws_profile
  default_tags {{
    tags = local.common_tags
  }}
}}

locals {{
  common_tags = {{
{tags_block}
  }}
}}

# Latest Ubuntu 22.04 LTS ARM64 AMI (Canonical)
data "aws_ssm_parameter" "ubuntu_lts" {{
  name = "/aws/service/canonical/ubuntu/server/22.04/stable/current/arm64/hvm/ebs-gp2/ami-id"
}}

resource "aws_key_pair" "jumphost" {{
  key_name   = "{naming_prefix}-jumphost-key"
  public_key = file(var.public_key_path)
}}

resource "aws_security_group" "jumphost" {{
  name        = "{naming_prefix}-jumphost-sg"
  description = "aws-skill jumphost SG for {customer}"
}}

resource "aws_security_group_rule" "jumphost_ssh" {{
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  cidr_blocks       = ["{allowed_cidr}"]
  security_group_id = aws_security_group.jumphost.id
  description       = "aws-skill ingress"
}}

resource "aws_security_group_rule" "jumphost_egress_all" {{
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  cidr_blocks       = ["0.0.0.0/0"]
  security_group_id = aws_security_group.jumphost.id
}}

resource "aws_instance" "jumphost" {{
  ami                    = data.aws_ssm_parameter.ubuntu_lts.value
  instance_type          = "{instance_type}"
  key_name               = aws_key_pair.jumphost.key_name
  vpc_security_group_ids = [aws_security_group.jumphost.id]
  user_data              = file("${{path.module}}/user-data.sh")

  root_block_device {{
    volume_size           = 20
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }}

  metadata_options {{
    http_tokens   = "required"
    http_endpoint = "enabled"
    instance_metadata_tags = "enabled"
  }}

  tags = {{
    Name = "{naming_prefix}-jumphost"
  }}
}}

resource "aws_eip" "jumphost" {{
  domain = "vpc"
  tags = {{
    Name = "{naming_prefix}-jumphost-eip"
  }}
}}

resource "aws_eip_association" "jumphost" {{
  instance_id   = aws_instance.jumphost.id
  allocation_id = aws_eip.jumphost.id
}}
"""


def _render_variables_tf(*, naming_prefix: str) -> str:
    return """variable "aws_profile" {
  description = "AWS profile to use (matches ~/.aws/config)."
  type        = string
  default     = "epoch"
}

variable "public_key_path" {
  description = "Path to the SSH public key file to register on the jumphost."
  type        = string
  default     = "~/.ssh/aws-skill-jumphost.pub"
}
"""


def _render_outputs_tf() -> str:
    return """output "instance_id" {
  value = aws_instance.jumphost.id
}

output "public_ip" {
  value = aws_eip.jumphost.public_ip
}

output "ssh_hint" {
  value = "ssh -i ${replace(var.public_key_path, ".pub", "")} ubuntu@${aws_eip.jumphost.public_ip}"
}
"""


def _render_tag_block(tags: dict[str, str], indent: str = "  ") -> str:
    return "\n".join(f'{indent}{k} = "{v}"' for k, v in tags.items())


def _read_user_data(naming_prefix: str, allowed_ip: str) -> str:
    user_data_path = SKILL_ROOT / "templates" / "jumphost-userdata.sh"
    text = user_data_path.read_text()
    return (
        text.replace("{{HOSTNAME}}", f"{naming_prefix}-jumphost-host")
        .replace("{{ALLOWED_IP}}", allowed_ip)
    )
